dist: trusty
sudo: false
language: node_js
node_js: node

install:
- npm ci
cache:
  directories:
  - $HOME/.npm

stages:
  - name: linting
  - name: testing
  - name: building
  - name: deploying
    if: branch = master
#  - name: publishing
#    if: branch = master

git:
  depth: 3

jobs:
  include:
    - stage: linting
      script: npm run lint
    - stage: testing
      script: npm run test
    - stage: building
      script: npm run build
    - stage: deploying
      before_deploy:
        - npm install
        - npm run deploy
        - cp dist/apps/ng-lab-demo/index.html dist/apps/ng-lab-demo/404.html
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: "$GH_TOKEN"
        keep-history: true
        local-dir: dist/apps/ng-lab-demo
        on:
          branch: master
#    - stage: publishing
#      if: branch = master
#      before_install:
        # Clone the whole repository because we also need the develop branch for releasing
#        - git clone "https://github.com/$TRAVIS_REPO_SLUG.git" "$TRAVIS_REPO_SLUG";
#        - cd "$TRAVIS_REPO_SLUG";
#        - git checkout -qf "$TRAVIS_COMMIT";
        #  Fix Travis CI issue of detached heads in git
#        - git checkout master
#      install:
#        - npm install
#        - npm run build
#      before_deploy:
        # Login to Git to be able to make commits (required by automatic-release)
#        - git config --global user.name "Miguel Ramos"; # REPLACE!
#        - git config --global user.email "miguel.marques.ramos@gmail.com"; # REPLACE!
#        - git config credential.helper "store --file=.git/credentials";
#        - echo "https://$GH_TOKEN:@github.com" > .git/credentials;
        # Run automatic-release
#        - npm run release
#      deploy:
#        provider: script
#        script: bash tools/scripts/publish.sh
#        api_key: "$NPM_TOKEN"
#        skip_cleanup: true
#        on:
#          branch: master

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
