dist: trusty
sudo: false
language: node_js
node_js: node

install:
- npm ci
cache:
  directories:
  - $HOME/.npm
#script:
#- npm run lint
#- npm run test
#- npm run build

#deploy:
#  provider: pages
#  skip-cleanup: true
#  github-token: $GITHUB_TOKEN
#  keep-history: true
#  local-dir: dist/ng-lab
#  on:
#    branch: master
stages:
  - linting
  - testing
  - building

git:
  depth: 3

jobs:
  include:
    - stage: linting
      script: npm run lint
    - stage: testing
      script: npm run test
    - stage: building
      script: npm run build
#after_success:
#  - npm run travis-deploy-once "npm run semantic-release"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
